# Generated by Django 4.1.4 on 2023-02-19 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CompanyModel",
            fields=[
                (
                    "company_name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("is_it_from_company", models.BooleanField()),
                (
                    "phone_no",
                    models.BigIntegerField(null=True, verbose_name="Phone Number"),
                ),
                (
                    "company_destination",
                    models.CharField(default="erode", max_length=20),
                ),
                (
                    "from_companies",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_companies_set",
                        to="records.companymodel",
                    ),
                ),
                (
                    "to_companies",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_companies_set",
                        to="records.companymodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecordModel",
            fields=[
                (
                    "courier_number",
                    models.IntegerField(
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="Courier Number",
                    ),
                ),
                (
                    "courier_type",
                    models.CharField(
                        choices=[("cash", "cash"), ("credit", "credit")],
                        default="cash",
                        max_length=6,
                        verbose_name="Courier Type",
                    ),
                ),
                (
                    "courier_company",
                    models.CharField(
                        choices=[("akash", "akash"), ("anjani", "anjani")],
                        default="akash",
                        max_length=6,
                        verbose_name="Courier Company",
                    ),
                ),
                (
                    "to_destination",
                    models.CharField(max_length=20, verbose_name="To Destination"),
                ),
                (
                    "courier_weight",
                    models.FloatField(default=100, verbose_name="Courier Weight"),
                ),
                (
                    "courier_rate",
                    models.PositiveSmallIntegerField(
                        default=40, verbose_name="Courier Rate"
                    ),
                ),
                (
                    "phone_no",
                    models.BigIntegerField(null=True, verbose_name="Phone Number"),
                ),
                (
                    "booked_date",
                    models.DateField(auto_now=True, verbose_name="Booked Date"),
                ),
                (
                    "booked_time",
                    models.TimeField(auto_now=True, verbose_name="Booked Time"),
                ),
                ("is_paid", models.BooleanField(default=False, verbose_name="Is Paid")),
                (
                    "from_company",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="from_company",
                        to="records.companymodel",
                    ),
                ),
                (
                    "to_company",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="to_company",
                        to="records.companymodel",
                    ),
                ),
            ],
        ),
    ]
