# Generated by Django 4.1.4 on 2022-12-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordModel',
            fields=[
                ('courier_number', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Courier Number')),
                ('courier_type', models.CharField(default='cash', max_length=6, verbose_name='Courier Type')),
                ('courier_company', models.CharField(default='anjani', max_length=6, verbose_name='Courier Company')),
                ('from_company', models.CharField(max_length=50, verbose_name='From Company')),
                ('to_company', models.CharField(max_length=50, verbose_name='To Company')),
                ('to_destination', models.CharField(max_length=20, verbose_name='To Destination')),
                ('courier_weight', models.FloatField(default=100, verbose_name='Courier Weight')),
                ('courier_rate', models.PositiveSmallIntegerField(default=40, verbose_name='Courier Rate')),
                ('phone_no', models.IntegerField(blank=True, null=True, verbose_name='Phone Number')),
                ('booked_date', models.DateField(auto_now=True, verbose_name='Booked Date')),
                ('booked_time', models.TimeField(auto_now=True, verbose_name='Booked Time')),
            ],
        ),
    ]
