# Generated by Django 4.1.4 on 2023-02-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companymodel",
            name="from_companies",
        ),
        migrations.RemoveField(
            model_name="companymodel",
            name="to_companies",
        ),
        migrations.AddField(
            model_name="companymodel",
            name="from_companies",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="from_companies_set",
                to="records.companymodel",
            ),
        ),
        migrations.AddField(
            model_name="companymodel",
            name="to_companies",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="to_companies_set",
                to="records.companymodel",
            ),
        ),
    ]
