# Generated by Django 4.1.4 on 2023-02-26 14:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0002_remove_companymodel_from_companies_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="companymodel",
            name="from_companies",
            field=models.ManyToManyField(blank=True, to="records.companymodel"),
        ),
        migrations.AlterField(
            model_name="companymodel",
            name="to_companies",
            field=models.ManyToManyField(blank=True, to="records.companymodel"),
        ),
    ]
