# Generated by Django 4.1.4 on 2023-02-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0003_alter_companymodel_from_companies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="companymodel",
            name="is_it_cash",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
