version: '3.9'
services:
  frontend:
    image: goameer030/cb-frontend:latest
    build: ./Frontend/.
    container_name: frontend
    environment:
      - VITE_BACKEND_ADDRESS=${BACKEND_URL}
    ports:
      - 5173:5173
    volumes:
      - ./Frontend:/Frontend
    links:
      - backend
    depends_on:
      - backend

  backend:
    image: goameer030/cb-backend:latest
    build:
      context: ./Backend/.
      args:
        - ENV=DEVELOPMENT
    container_name: backend
    environment:
      - ENV=DEVELOPMENT

      - BACKEND_URL=${BACKEND_URL}

      - MAIL_ID=${MAIL_ID}
      - MAIL_PASSWORD=${MAIL_PASSWORD}

      - AKASH_USER_ID=${AKASH_USER_ID}
      - AKASH_PASSWORD=${AKASH_PASSWORD}
      - ANJANI_USER_ID=${ANJANI_USER_ID}
      - ANJANI_PASSWORD=${ANJANI_PASSWORD}

      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
    ports:
      - 8000:8000
    volumes:
      - ./Backend:/Backend
    links:
      - redis
      - celery
      - selenium
    depends_on:
      - celery
      - selenium

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    environment:
      - SE_NODE_MAX_CONCURRENT_SESSIONS=2
    expose:
      - 4444
    ports:
      - 4444:4444

  celery:
    build: 
      context: ./Backend/.
      args:
        - ENV=DEVELOPMENT
    container_name: celery
    command: celery -A backend worker -l info
    volumes:
      - ./Backend:/Backend
    links:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    ports:
      - 6379:6379
