version: '3.9'
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    links:
      - backend
    depends_on:
      - backend
      - frontend
  frontend:
    image: goameer030/cb-frontend:latest
    build: ./Frontend/.
    container_name: frontend
    ports:
      - 5173:5173
    volumes:
      - ./Frontend:/Frontend
    links:
      - backend
    depends_on:
      - backend

  backend:
    image: goameer030/cb-backend:latest
    build: ./Backend/.
    container_name: backend
    environment:
      - MAIL_PASSWORD=${MAIL_PASSWORD}
      - AKASH_USER_ID=${AKASH_USER_ID}
      - AKASH_PASSWORD=${AKASH_PASSWORD}
      - ANJANI_USER_ID=${ANJANI_USER_ID}
      - ANJANI_PASSWORD=${ANJANI_PASSWORD}
    ports:
      - 8000:8000
    volumes:
      - ./Backend:/Backend
    links:
      - redis
      - celery
      - selenium
    depends_on:
      - celery
      - selenium

  selenium:
    image: selenium/standalone-chrome
    container_name: selenium
    environment:
      - SE_NODE_MAX_CONCURRENT_SESSIONS=2
    expose:
      - 4444
    ports:
      - 4444:4444

  celery:
    build: ./Backend/
    container_name: celery
    command: celery -A backend worker -l info
    volumes:
      - ./Backend:/Backend
    links:
      - redis

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - 6379
    ports:
      - 6379:6379
