# Generated by Django 4.1.4 on 2023-01-15 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DRSRecordModel',
            fields=[
                ('courier_number', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Courier Number')),
                ('drs_data', models.TextField(verbose_name='DRS Details')),
            ],
        ),
    ]
