# Generated by Django 4.1.4 on 2023-01-28 09:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('webscarper', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drsrecordmodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created At'),
            preserve_default=False,
        ),
    ]
